services:
  minio:
    image: minio/minio
    container_name: minio
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadminpassword
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./data/minio:/data
      
  cassandra-seed:
    image: cassandra:4.1.9
    container_name: cassandra-seed
    environment:
      - CASSANDRA_CLUSTER_NAME=remsfal-cassandra-cluster
      - CASSANDRA_NUM_TOKENS=8
      - CASSANDRA_SEEDS=cassandra-seed
      - CASSANDRA_USER=admin
      - CASSANDRA_PASSWORD=admin
    ports:
      - "9042:9042"
      - "7000:7000"

  cassandra-node1:
    image: cassandra:4.1.9
    container_name: cassandra-node1
    environment:
      - CASSANDRA_CLUSTER_NAME=remsfal-cassandra-cluster
      - CASSANDRA_SEEDS=cassandra-seed
    ports:
      - "9043:9042" # Alternative port mapping for node1
      - "7001:7000"

  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_LISTENERS=DOCKER_INTERNAL://kafka:29092,HOST_EXTERNAL://0.0.0.0:9092,CONTROLLER://kafka:9093
      - KAFKA_ADVERTISED_LISTENERS=DOCKER_INTERNAL://kafka:29092,HOST_EXTERNAL://localhost:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=DOCKER_INTERNAL:PLAINTEXT,HOST_EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=DOCKER_INTERNAL
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
      - KAFKA_NUM_PARTITIONS=1

  ocr:
    image: remsfal-ocr
    container_name: remsfal-ocr
    environment:
      - KAFKA_BROKER=kafka:29092
      - MINIO_ENDPOINT=minio:9000
      - PYTHONUNBUFFERED=1
